<h1>Contact US</h1>
<script src="<?php echo $this->url->get("ckeditor/ckeditor.js"); ?>" ></script>
<script src='http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7'></script>
<script src="<?php echo $this->url->get("js/maplace/maplace-0.1.3.min.js"); ?>" ></script>
<div class='row'>
    <div class='col-md-6'>
        <?php echo $this->getContent(); ?>
        <form method="post">

            <!-- First Name !-->
            <?php echo $form->renderDecorated('name'); ?>

            <!-- Email !-->
            <?php echo $form->renderDecorated('email'); ?>

            <!-- Section !-->
            <?php echo $form->renderDecorated('section'); ?>

            <!-- Password !-->
            <?php echo $form->renderDecorated('message'); ?>

            <br/>
            <!-- Submit !-->
            <?php echo $form->renderDecorated('submit'); ?>

        </form>

    </div>
    <div class='col-md-6'>
        <!-- Map !-->
        <?php echo $form->renderDecorated('map'); ?>
    </div>
</div>

