<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Website Info</h2>
                </header>
                <div class="panel-body">

                    <p>You can change website info here</p>

                    <!-- Website Name !-->
                    <?php $siteInfoForm->renderDecorated("websitename"); ?>

                    <!-- Footer Text !-->
                    <?php $siteInfoForm->renderDecorated("footername"); ?>

                    <!-- Offline Message !-->
                    <?php $siteInfoForm->renderDecorated("offlinemessage"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
    <!-- SEO !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">SEO</h2>
                </header>
                <div class="panel-body">
                    <p>In order to change your search engine rank, you may define your SEO options right there</p>

                    <!-- keywords !-->
                    <?php $siteInfoForm->renderDecorated("keywords"); ?>

                    <!-- keywords !-->
                    <?php $siteInfoForm->renderDecorated("metadata"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
    <!-- Location !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Location</h2>
                </header>
                <div class="panel-body">
                    <p>You can define your location right there</p>

                    <!-- latitude !-->
                    <?php $siteInfoForm->renderDecorated("latitude"); ?>

                    <!-- longtude !-->
                    <?php $siteInfoForm->renderDecorated("longtude"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
</form>