<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">FAQ'S</h2>
    </header>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-condensed mb-none ">
                <tr>
                    <th>ID</th>
                    <th>Head</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
                <?php foreach ($list->items as $item) { ?>
                    <tr>
                        <td><?php echo $item->id; ?></td>
                        <td><?php echo $item->head; ?></td>
                        <td><?php echo $item->title; ?></td>
                        <td><?php echo $item->message ?></td>
                        <td>
                            <a href="<?php echo $this->url->get("faq/view/" . $item->id); ?>" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                            <a href="<?php echo $this->url->get("faq/delete/" . $item->id); ?>" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <!-- Paginatoing Items !-->
        <div class="center">
            <div class="pagination pagination-centered">
                <li><a class="pag" href="<?php echo $this->url->get("user/list/") ?>">First</a> </li>
                <li> <a href="<?php echo $this->url->get("user/list/$list->before") ?>">Previous</a></li>
                <li> <a href="<?php echo $this->url->get("user/list/$list->next") ?>">Next</a></li>
                <li> <a href="<?php echo $this->url->get("user/list/$list->last") ?>">Last</a></li>
            </div>
            <div>
                <?php echo "You are in page ", $list->current, " of ", $list->total_pages; ?>
            </div>
        </div>
    </div>
</section>


