<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">Email Templates</h2>
    </header>
    <div class="panel-body">
        <p class="pull-left">Here you can edit the email templates or add new email template to the system</p>
        <a class="btn btn-primary pull-right" href="<?php echo $this->url->get("emailtemplate/add"); ?>">Add Template</a>
        <br/>
        <br/>
        <hr style="clear: both;"/>
        <table class="table table-bordered table-hover">
            <th>
                Name
            </th>
            <th>
                Action
            </th>

            <?php foreach ($templates as $template): ?>
                <tr>
                    <td>
                        <?php echo $template->name; ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url->get("emailtemplate/view/" . $template->name); ?>" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                        <a href="<?php echo $this->url->get("emailtemplate/delete/" . $template->name); ?>" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</section>


